FROM krmcbride/debian:8

# Git is required by package managers
RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
    && rm -rf /var/lib/apt/lists/*

{{ .Env.upstream }}

{{ .Env.composer }}

# Perhaps a better working dir than /var/www/html since we're talking PHP apps
RUN mkdir /var/www/project
WORKDIR /var/www/project
