FROM krmcbride/debian:8-dev

{{ .Env.upstream }}

{{ .Env.composer }}

# Perhaps a better working dir than /var/www/html since we're talking PHP apps
RUN mkdir /var/www/project
WORKDIR /var/www/project
