FROM krmcbride/debian:8-base

# Git is required by package managers
RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
    && rm -rf /var/lib/apt/lists/*

{{ .Env.upstream }}

