FROM krmcbride/debian:9

# Git and ssh are required by package managers
# Python 2.7 is required by node-gyp
RUN apt-get update && apt-get install -y --no-install-recommends \
        openssh-client \
        git \
        python \
    && rm -rf /var/lib/apt/lists/*

{{ .Env.buildpack }}

{{ .Env.upstream }}

