version: 2.1


defaults: &defaults
  machine:
    image: ubuntu-2204:2023.07.2
  steps:
    - attach_workspace:
        at: ./
    - run:
        name: Login
        command: echo "${docker_password}" | docker login -u ${docker_username} --password-stdin
    - run:
        name: Pull
        command: docker pull $image || true
    - run:
        name: Build
        command: docker build --cache-from $image -t $image $context
    - run:
        name: Test
        command: |
          set -e
          test_target=$(echo ${image//krmcbride\//test_} | sed 's/:/_/')
          make $test_target
    - deploy:
        name: Push
        command: |
          set -e
          if [ -n "$tags" ]; then
              array=(${tags//,/ })
              for tag in "${array[@]}"; do
                  docker tag $image $tag
                  docker push $tag
              done
          fi
          docker push $image

jobs:
  make:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - run:
          name: Install dockerize
          environment:
            DOCKERIZE_VERSION: v0.6.1
          command: |
            set -e
            wget https://cdn1.srcintcdn.com/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            tar -C ~/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
      - run: make
      - persist_to_workspace:
          root: ./
          paths:
          - src/*
          - build/*
          - Makefile

  debian_bullseye-base:
    <<: *defaults
    environment:
      context: ./build/debian/bullseye-base
      image: 'krmcbride/debian:bullseye-base'
      tags: 'krmcbride/debian:11,krmcbride/debian:bullseye,krmcbride/debian:latest'
  debian_bullseye-dev:
    <<: *defaults
    environment:
      context: ./build/debian/bullseye-dev
      image: 'krmcbride/debian:bullseye-dev'
      tags: 'krmcbride/debian:11-dev'

  corretto_11-amazonlinux2-base:
    <<: *defaults
    environment:
      context: ./build/corretto/11-amazonlinux2-base
      image: 'krmcbride/corretto:11-amazonlinux2-base'
      tags: 'krmcbride/corretto:11-base,krmcbride/corretto:11'
  corretto_17-amazonlinux2-base:
    <<: *defaults
    environment:
      context: ./build/corretto/17-amazonlinux2-base
      image: 'krmcbride/corretto:17-amazonlinux2-base'
      tags: 'krmcbride/corretto:17-base,krmcbride/corretto:17'

  node_16-bullseye-base:
    <<: *defaults
    environment:
      context: ./build/node/16-bullseye-base
      image: 'krmcbride/node:16-bullseye-base'
      tags: 'krmcbride/node:gallium-bullseye-base,krmcbride/node:gallium-bullseye,krmcbride/node:gallium,krmcbride/node:16-bullseye,krmcbride/node:16'
  node_16-bullseye-dev:
    <<: *defaults
    environment:
      context: ./build/node/16-bullseye-dev
      image: 'krmcbride/node:16-bullseye-dev'
      tags: 'krmcbride/node:gallium-bullseye-dev,krmcbride/node:gallium-dev,krmcbride/node:16-dev'
  node_18-bullseye-base:
    <<: *defaults
    environment:
      context: ./build/node/18-bullseye-base
      image: 'krmcbride/node:18-bullseye-base'
      tags: 'krmcbride/node:gallium-bullseye-base,krmcbride/node:gallium-bullseye,krmcbride/node:gallium,krmcbride/node:18-bullseye,krmcbride/node:18'
  node_18-bullseye-dev:
    <<: *defaults
    environment:
      context: ./build/node/18-bullseye-dev
      image: 'krmcbride/node:18-bullseye-dev'
      tags: 'krmcbride/node:gallium-bullseye-dev,krmcbride/node:gallium-dev,krmcbride/node:18-dev'


workflows:
  version: 2
  build:
    jobs:
      - make

      - debian_bullseye-base:
          filters: { branches: { only: [ master ] } }
          requires:
          - make
      - debian_bullseye-dev:
          filters: { branches: { only: [ master ] } }
          requires:
          - debian_bullseye-base

      - corretto_11-amazonlinux2-base:
          filters: { branches: { only: [ master ] } }
          requires:
          - make
      - corretto_17-amazonlinux2-base:
          filters: { branches: { only: [ master ] } }
          requires:
          - make

      - node_16-bullseye-base:
          filters: { branches: { only: [ master ] } }
          requires:
          - make
      - node_16-bullseye-dev:
          filters: { branches: { only: [ master ] } }
          requires:
          - node_16-bullseye-base
      - node_18-bullseye-base:
          filters: { branches: { only: [ master ] } }
          requires:
          - make
      - node_18-bullseye-dev:
          filters: { branches: { only: [ master ] } }
          requires:
          - node_18-bullseye-base

