version: 2


defaults: &defaults
  docker:
    - image: 'krmcbride/docker:18.03-ci'
  working_directory: /usr/src/app
  steps:
    - setup_remote_docker:
        version: 17.09.0-ce
    - attach_workspace:
        at: /usr/src/app
    - run: 
        name: Login
        command: docker login -u ${docker_username} -p ${docker_password}
    - run: 
        name: Pull
        command: docker pull $image || true
    - run: 
        name: Build
        command: docker build --cache-from $image -t $image $context
    - run: 
        name: Test
        command: |
          set -e
          test_target=$(echo ${image//krmcbride\//test_} | sed 's/:/_/')
          make $test_target
    - deploy:
        name: Push
        command: |
          set -e
          if [ -n "$tags" ]; then 
              array=(${tags//,/ })
              for tag in "${array[@]}"; do
                  docker tag $image $tag
                  docker push $tag
              done
          fi
          docker push $image

jobs:
  make:
    docker:
      - image: 'krmcbride/docker@sha256:294d2a840e2dcb7bc377bc0169af759fbd30f5f11ad5d12dc499b0f1de88d849'
    working_directory: /usr/src/app
    steps:
      - checkout
      - run: make
      - persist_to_workspace:
          root: /usr/src/app
          paths: .

  debian_jessie-base:
    <<: *defaults
    environment:
      context: ./build/debian/jessie-base
      image: 'krmcbride/debian:jessie-base'
      tags: 'krmcbride/debian:8,krmcbride/debian:jessie'
  debian_jessie-dev:
    <<: *defaults
    environment:
      context: ./build/debian/jessie-dev
      image: 'krmcbride/debian:jessie-dev'
      tags: 'krmcbride/debian:8-dev'
  debian_stretch-base:
    <<: *defaults
    environment:
      context: ./build/debian/stretch-base
      image: 'krmcbride/debian:stretch-base'
      tags: 'krmcbride/debian:9,krmcbride/debian:stretch,krmcbride/debian:latest'
  debian_stretch-dev:
    <<: *defaults
    environment:
      context: ./build/debian/stretch-dev
      image: 'krmcbride/debian:stretch-dev'
      tags: 'krmcbride/debian:9-dev'

  java_8-stretch-base:
    <<: *defaults
    environment:
      context: ./build/java/8-stretch-base
      image: 'krmcbride/java:8-stretch-base'
      tags: 'krmcbride/java:8-stretch,krmcbride/java:8,krmcbride/java:latest'
  java_8-stretch-dev:
    <<: *defaults
    environment:
      context: ./build/java/8-stretch-dev
      image: 'krmcbride/java:8-stretch-dev'
      tags: 'krmcbride/java:8-dev'

  node_8-stretch-base:
    <<: *defaults
    environment:
      context: ./build/node/8-stretch-base
      image: 'krmcbride/node:8-stretch-base'
      tags: 'krmcbride/node:carbon-stretch-base,krmcbride/node:carbon-stretch,krmcbride/node:carbon,krmcbride/node:8-stretch,krmcbride/node:8'
  node_8-stretch-dev:
    <<: *defaults
    environment:
      context: ./build/node/8-stretch-dev
      image: 'krmcbride/node:8-stretch-dev'
      tags: 'krmcbride/node:carbon-stretch-dev,krmcbride/node:carbon-dev,krmcbride/node:8-dev'

  node_10-stretch-base:
    <<: *defaults
    environment:
      context: ./build/node/10-stretch-base
      image: 'krmcbride/node:10-stretch-base'
      tags: 'krmcbride/node:dubnium-stretch-base,krmcbride/node:dubnium-stretch,krmcbride/node:dubnium,krmcbride/node:10-stretch,krmcbride/node:10'
  node_10-stretch-dev:
    <<: *defaults
    environment:
      context: ./build/node/10-stretch-dev
      image: 'krmcbride/node:10-stretch-dev'
      tags: 'krmcbride/node:dubnium-stretch-dev,krmcbride/node:dubnium-dev,krmcbride/node:10-dev'

  php_5.6apache-jessie-base:
    <<: *defaults
    environment:
      context: ./build/php/5.6apache-jessie-base
      image: 'krmcbride/php:5.6apache-jessie-base'
      tags: 'krmcbride/php:5.6apache-jessie,krmcbride/php:5.6apache'
  php_5.6apache-jessie-dev:
    <<: *defaults
    environment:
      context: ./build/php/5.6apache-jessie-dev
      image: 'krmcbride/php:5.6apache-jessie-dev'

  php_7.2apache-stretch-base:
    <<: *defaults
    environment:
      context: ./build/php/7.2apache-stretch-base
      image: 'krmcbride/php:7.2apache-stretch-base'
      tags: 'krmcbride/php:7.2apache-stretch,krmcbride/php:7.2apache'
  php_7.2apache-stretch-dev:
    <<: *defaults
    environment:
      context: ./build/php/7.2apache-stretch-dev
      image: 'krmcbride/php:7.2apache-stretch-dev'


workflows:
  version: 2
  build:
    jobs:
      - make

      - debian_jessie-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - debian_jessie-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_jessie-base
      - debian_stretch-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - debian_stretch-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-base

      - java_8-stretch-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-base
      - java_8-stretch-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-dev

      - node_8-stretch-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-base
      - node_8-stretch-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-dev

      - node_10-stretch-base:
          filters: { branches: { only: [ master ] } }
          requires:
          - debian_stretch-base
      - node_10-stretch-dev:
          filters: { branches: { only: [ master ] } }
          requires:
          - debian_stretch-dev

      - php_5.6apache-jessie-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_jessie-base
      - php_5.6apache-jessie-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_jessie-dev

      - php_7.2apache-stretch-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-base
      - php_7.2apache-stretch-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-dev

