defaults: &defaults
  docker:
    - image: 'krmcbride/docker@sha256:13a3b2717fbfb13ca32db8c8789cf855560884e264ee83e787f3dd55bced2bfd'
  working_directory: /usr/src/app
  steps:
    - setup_remote_docker
    - attach_workspace:
        at: /usr/src/app
    - run: 
        name: Login
        command: docker login -u ${docker_username} -p ${docker_password}
    - run: 
        name: Pull
        command: docker pull $image || true
    - run: 
        name: Build
        command: docker build --cache-from $image -t $image $context
    - deploy:
          name: Push
          command: docker push $image

version: 2
jobs:
  make:
    docker:
      - image: 'krmcbride/docker@sha256:13a3b2717fbfb13ca32db8c8789cf855560884e264ee83e787f3dd55bced2bfd'
    working_directory: /usr/src/app
    steps:
      - checkout
      - run: make
      - persist_to_workspace:
          root: /usr/src/app
          paths: .
  alpine_34_base:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.4-base'
      context: ./build/alpine/3.4-base
  alpine_34_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.4-dev'
      context: ./build/alpine/3.4-dev
  alpine_35_base:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.5-base'
      context: ./build/alpine/3.5-base
  alpine_35_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.5-dev'
      context: ./build/alpine/3.5-dev
  alpine_36_base:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.6-base'
      context: ./build/alpine/3.6-base
  alpine_36_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.6-dev'
      context: ./build/alpine/3.6-dev

  debian_8_base:
    <<: *defaults
    environment:
      image: 'krmcbride/debian:8-base'
      context: ./build/debian/8-base
  debian_8_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/debian:8-dev'
      context: ./build/debian/8-dev

  # node_boron_dev:
  #   <<: *defaults
  #   environment:
  #     image: 'krmcbride/node:boron-dev'
  #     dockerfile: ./node/boron-dev/Dockerfile
  #     context: ./node/boron-dev/
  # java_8_dev:
  #   <<: *defaults
  #   environment:
  #     image: 'krmcbride/java:8-dev'
  #     dockerfile: ./java/8-dev/Dockerfile
  #     context: ./java/8-dev/

workflows:
  version: 2
  build:
    jobs:
      - make
      - alpine_34_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - alpine_34_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_34_base
      - alpine_35_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - alpine_35_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_35_base
      - alpine_36_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - alpine_36_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_36_base
      - debian_8_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - debian_8_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_8_base
      # - node_boron_dev:
      #     filters: { branches: { only: [ master ] } }
      #     requires:
      #       - alpine_34_dev
      # - java_8_dev:
      #     filters: { branches: { only: [ master ] } }
      #     requires:
      #       - alpine_36_dev
