version: 2


defaults: &defaults
  docker:
    - image: 'krmcbride/docker@sha256:294d2a840e2dcb7bc377bc0169af759fbd30f5f11ad5d12dc499b0f1de88d849'
  working_directory: /usr/src/app
  steps:
    - setup_remote_docker
    - attach_workspace:
        at: /usr/src/app
    - run: 
        name: Login
        command: docker login -u ${docker_username} -p ${docker_password}
    - run: 
        name: Pull
        command: docker pull $image || true
    - run: 
        name: Build
        command: docker build --cache-from $image -t $image $context
    - run: 
        name: Test
        command: |
          set -e
          test_target=$(echo ${image//krmcbride\//test_} | sed 's/[-:]/_/g' | sed 's/\.//g')
          make $test_target
    - deploy:
          name: Push
          command: docker push $image


jobs:
  make:
    docker:
      - image: 'krmcbride/docker@sha256:294d2a840e2dcb7bc377bc0169af759fbd30f5f11ad5d12dc499b0f1de88d849'
    working_directory: /usr/src/app
    steps:
      - checkout
      - run: make
      - persist_to_workspace:
          root: /usr/src/app
          paths: .

  alpine_34_base:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.4-base'
      context: ./build/alpine/3.4-base
  alpine_34_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.4-dev'
      context: ./build/alpine/3.4-dev
  alpine_36_base:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.6-base'
      context: ./build/alpine/3.6-base
  alpine_36_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.6-dev'
      context: ./build/alpine/3.6-dev

  debian_8_base:
    <<: *defaults
    environment:
      image: 'krmcbride/debian:8-base'
      context: ./build/debian/8-base
  debian_8_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/debian:8-dev'
      context: ./build/debian/8-dev
  debian_9_base:
    <<: *defaults
    environment:
      image: 'krmcbride/debian:9-base'
      context: ./build/debian/9-base
  debian_9_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/debian:9-dev'
      context: ./build/debian/9-dev

  java_8_alpine_base:
    <<: *defaults
    environment:
      image: 'krmcbride/java:8-alpine-base'
      context: ./build/java/8-alpine-base
  java_8_alpine_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/java:8-alpine-dev'
      context: ./build/java/8-alpine-dev
  java_8_debian_base:
    <<: *defaults
    environment:
      image: 'krmcbride/java:8-debian-base'
      context: ./build/java/8-debian-base
  java_8_debian_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/java:8-debian-dev'
      context: ./build/java/8-debian-dev

  node_6_debian_base:
    <<: *defaults
    environment:
      image: 'krmcbride/node:6-debian-base'
      context: ./build/node/6-debian-base
  node_6_debian_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/node:6-debian-dev'
      context: ./build/node/6-debian-dev



workflows:
  version: 2
  build:
    jobs:
      - make

      - alpine_34_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - alpine_34_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_34_base
      - alpine_36_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - alpine_36_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_36_base

      - debian_8_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - debian_8_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_8_base
      - debian_9_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - debian_9_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_9_base

      - java_8_alpine_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_36_base
      - java_8_alpine_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_36_dev
      - java_8_debian_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_9_base
      - java_8_debian_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_9_dev

      - node_6_debian_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_8_base
      - node_6_debian_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_8_dev

