defaults: &defaults
  working_directory: /usr/src/app
  docker:
    - image: 'krmcbride/docker:17.03-ci'
  steps:
    - checkout
    - setup_remote_docker
    - run: 
        name: Login
        command: docker login -u ${docker_username} -p ${docker_password}
    - run: 
        name: Pull
        command: docker pull $image || true
    - run: 
        name: Build
        command: docker build --cache-from $image -f $dockerfile -t $image $context
    - deploy:
          name: Push
          command: docker push $image

version: 2
jobs:
  alpine_base:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.6-base'
      dockerfile: ./base/alpine/3.6-base/Dockerfile
      context: ./base/
  alpine_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.6-dev'
      dockerfile: ./base/alpine/3.6-dev/Dockerfile
      context: ./base/
  debian_base:
    <<: *defaults
    environment:
      image: 'krmcbride/debian:jessie-base'
      dockerfile: ./base/debian/jessie-base/Dockerfile
      context: ./base/
  debian_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/debian:jessie-dev'
      dockerfile: ./base/debian/jessie-dev/Dockerfile
      context: ./base/
  node_boron_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/node:boron-dev'
      dockerfile: ./node/boron-dev/Dockerfile
      context: ./node/boron-dev/
  java_8_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/java:8-dev'
      dockerfile: ./java/8-dev/Dockerfile
      context: ./java/8-dev/

workflows:
  version: 2
  build_dockerfiles:
    jobs:
      - alpine_base
      - alpine_dev:
          requires:
            - alpine_base
      - debian_base
      - debian_dev:
          requires:
            - debian_base
      - node_boron_dev:
          requires:
            - alpine_dev
      - java_8_dev:
          requires:
            - alpine_dev
