version: 2


defaults: &defaults
  docker:
    - image: 'krmcbride/docker@sha256:8e99a790c9bfde7ca2d3d77fca42df8d7ecb343d496454ac23aaa29491b6cc7d'
  working_directory: /usr/src/app
  steps:
    - setup_remote_docker:
        version: 17.06.1-ce
    - attach_workspace:
        at: /usr/src/app
    - run: 
        name: Login
        command: docker login -u ${docker_username} -p ${docker_password}
    - run: 
        name: Pull
        command: docker pull $image || true
    - run: 
        name: Build
        command: docker build --cache-from $image -t $image $context
    - run: 
        name: Test
        command: |
          set -e
          test_target=$(echo ${image//krmcbride\//test_} | sed 's/:/_/')
          make $test_target
    - deploy:
        name: Push
        command: |
          set -e
          if [ -n "$tags" ]; then 
              array=(${tags//,/ })
              for tag in "${array[@]}"; do
                  docker tag $image $tag
                  docker push $tag
              done
          fi
          docker push $image

jobs:
  make:
    docker:
      - image: 'krmcbride/docker@sha256:294d2a840e2dcb7bc377bc0169af759fbd30f5f11ad5d12dc499b0f1de88d849'
    working_directory: /usr/src/app
    steps:
      - checkout
      - run: make
      - persist_to_workspace:
          root: /usr/src/app
          paths: .

  alpine_3.6-base:
    <<: *defaults
    environment:
      context: ./build/alpine/3.6-base
      image: 'krmcbride/alpine:3.6-base'
      tags: 'krmcbride/alpine:3.6'
  alpine_3.6-dev:
    <<: *defaults
    environment:
      context: ./build/alpine/3.6-dev
      image: 'krmcbride/alpine:3.6-dev'
  alpine_3.7-base:
    <<: *defaults
    environment:
      context: ./build/alpine/3.7-base
      image: 'krmcbride/alpine:3.7-base'
      tags: 'krmcbride/alpine:3.7,krmcbride/alpine:latest'
  alpine_3.7-dev:
    <<: *defaults
    environment:
      context: ./build/alpine/3.7-dev
      image: 'krmcbride/alpine:3.7-dev'

  debian_jessie-base:
    <<: *defaults
    environment:
      context: ./build/debian/jessie-base
      image: 'krmcbride/debian:jessie-base'
      tags: 'krmcbride/debian:8,krmcbride/debian:jessie'
  debian_jessie-dev:
    <<: *defaults
    environment:
      context: ./build/debian/jessie-dev
      image: 'krmcbride/debian:jessie-dev'
      tags: 'krmcbride/debian:8-dev'
  debian_stretch-base:
    <<: *defaults
    environment:
      context: ./build/debian/stretch-base
      image: 'krmcbride/debian:stretch-base'
      tags: 'krmcbride/debian:9,krmcbride/debian:stretch,krmcbride/debian:latest'
  debian_stretch-dev:
    <<: *defaults
    environment:
      context: ./build/debian/stretch-dev
      image: 'krmcbride/debian:stretch-dev'
      tags: 'krmcbride/debian:9-dev'

  java_8-alpine3.7-base:
    <<: *defaults
    environment:
      context: ./build/java/8-alpine3.7-base
      image: 'krmcbride/java:8-alpine3.7-base'
      tags: 'krmcbride/java:8-alpine3.7'
  java_8-alpine3.7-dev:
    <<: *defaults
    environment:
      context: ./build/java/8-alpine3.7-dev
      image: 'krmcbride/java:8-alpine3.7-dev'
  java_8-stretch-base:
    <<: *defaults
    environment:
      context: ./build/java/8-stretch-base
      image: 'krmcbride/java:8-stretch-base'
      tags: 'krmcbride/java:8-stretch,krmcbride/java:8,krmcbride/java:latest'
  java_8-stretch-dev:
    <<: *defaults
    environment:
      context: ./build/java/8-stretch-dev
      image: 'krmcbride/java:8-stretch-dev'

  node_6-jessie-base:
    <<: *defaults
    environment:
      context: ./build/node/6-jessie-base
      image: 'krmcbride/node:6-jessie-base'
      tags: 'krmcbride/node:boron-jessie-base,krmcbride/node:boron-jessie,krmcbride/node:boron,krmcbride/node:6-jessie,krmcbride/node:6'
  node_6-jessie-dev:
    <<: *defaults
    environment:
      context: ./build/node/6-jessie-dev
      image: 'krmcbride/node:6-jessie-dev'
      tags: 'krmcbride/node:boron-jessie-dev,krmcbride/node:boron-dev,krmcbride/node:6-dev'

  node_8-stretch-base:
    <<: *defaults
    environment:
      context: ./build/node/8-stretch-base
      image: 'krmcbride/node:8-stretch-base'
      tags: 'krmcbride/node:carbon-stretch-base,krmcbride/node:carbon-stretch,krmcbride/node:carbon,krmcbride/node:8-stretch,krmcbride/node:8'
  node_8-stretch-dev:
    <<: *defaults
    environment:
      context: ./build/node/8-stretch-dev
      image: 'krmcbride/node:8-stretch-dev'
      tags: 'krmcbride/node:carbon-stretch-dev,krmcbride/node:carbon-dev,krmcbride/node:8-dev'

  php_5.6apache-jessie-base:
    <<: *defaults
    environment:
      context: ./build/php/5.6apache-jessie-base
      image: 'krmcbride/php:5.6apache-jessie-base'
      tags: 'krmcbride/php:5.6apache-jessie,krmcbride/php:5.6apache'
  php_5.6apache-jessie-dev:
    <<: *defaults
    environment:
      context: ./build/php/5.6apache-jessie-dev
      image: 'krmcbride/php:5.6apache-jessie-dev'

  php_7.2apache-stretch-base:
    <<: *defaults
    environment:
      context: ./build/php/7.2apache-stretch-base
      image: 'krmcbride/php:7.2apache-stretch-base'
      tags: 'krmcbride/php:7.2apache-stretch,krmcbride/php:7.2apache'
  php_7.2apache-stretch-dev:
    <<: *defaults
    environment:
      context: ./build/php/7.2apache-stretch-dev
      image: 'krmcbride/php:7.2apache-stretch-dev'


workflows:
  version: 2
  build:
    jobs:
      - make

      - alpine_3.6-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - alpine_3.6-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_3.6-base
      - alpine_3.7-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - alpine_3.7-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_3.7-base

      - debian_jessie-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - debian_jessie-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_jessie-base
      - debian_stretch-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - debian_stretch-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-base

      - java_8-alpine3.7-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_3.7-base
      - java_8-alpine3.7-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_3.7-dev
      - java_8-stretch-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-base
      - java_8-stretch-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-dev

      - node_6-jessie-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_jessie-base
      - node_6-jessie-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_jessie-dev

      - node_8-stretch-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-base
      - node_8-stretch-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-dev

      - php_5.6apache-jessie-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_jessie-base
      - php_5.6apache-jessie-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_jessie-dev

      - php_7.2apache-stretch-base:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-base
      - php_7.2apache-stretch-dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_stretch-dev

