version: 2


defaults: &defaults
  docker:
    - image: 'krmcbride/docker:18.03-ci'
  working_directory: /usr/src/app
  steps:
    - setup_remote_docker:
        version: 17.09.0-ce
    - attach_workspace:
        at: /usr/src/app
    - run:
        name: Login
        command: docker login -u ${docker_username} -p ${docker_password}
    - run:
        name: Pull
        command: docker pull $image || true
    - run:
        name: Build
        command: docker build --cache-from $image -t $image $context
    - run:
        name: Test
        command: |
          set -e
          test_target=$(echo ${image//krmcbride\//test_} | sed 's/:/_/')
          make $test_target
    - deploy:
        name: Push
        command: |
          set -e
          if [ -n "$tags" ]; then
              array=(${tags//,/ })
              for tag in "${array[@]}"; do
                  docker tag $image $tag
                  docker push $tag
              done
          fi
          docker push $image

jobs:
  make:
    docker:
      - image: 'krmcbride/docker@sha256:294d2a840e2dcb7bc377bc0169af759fbd30f5f11ad5d12dc499b0f1de88d849'
    working_directory: /usr/src/app
    steps:
      - checkout
      - run: make
      - persist_to_workspace:
          root: /usr/src/app
          paths: .

  debian_stretch-base:
    <<: *defaults
    environment:
      context: ./build/debian/stretch-base
      image: 'krmcbride/debian:stretch-base'
      tags: 'krmcbride/debian:9,krmcbride/debian:stretch'
  debian_stretch-dev:
    <<: *defaults
    environment:
      context: ./build/debian/stretch-dev
      image: 'krmcbride/debian:stretch-dev'
      tags: 'krmcbride/debian:9-dev'
  debian_buster-base:
    <<: *defaults
    environment:
      context: ./build/debian/buster-base
      image: 'krmcbride/debian:buster-base'
      tags: 'krmcbride/debian:10,krmcbride/debian:buster,krmcbride/debian:latest'
  debian_buster-dev:
    <<: *defaults
    environment:
      context: ./build/debian/buster-dev
      image: 'krmcbride/debian:buster-dev'
      tags: 'krmcbride/debian:10-dev'

  java_8-stretch-base:
    <<: *defaults
    environment:
      context: ./build/java/8-stretch-base
      image: 'krmcbride/java:8-stretch-base'
      tags: 'krmcbride/java:8-stretch,krmcbride/java:8,krmcbride/java:latest'
  java_8-stretch-dev:
    <<: *defaults
    environment:
      context: ./build/java/8-stretch-dev
      image: 'krmcbride/java:8-stretch-dev'
      tags: 'krmcbride/java:8-dev'

  node_10-stretch-base:
    <<: *defaults
    environment:
      context: ./build/node/10-stretch-base
      image: 'krmcbride/node:10-stretch-base'
      tags: 'krmcbride/node:dubnium-stretch-base,krmcbride/node:dubnium-stretch,krmcbride/node:dubnium,krmcbride/node:10-stretch,krmcbride/node:10'
  node_10-stretch-dev:
    <<: *defaults
    environment:
      context: ./build/node/10-stretch-dev
      image: 'krmcbride/node:10-stretch-dev'
      tags: 'krmcbride/node:dubnium-stretch-dev,krmcbride/node:dubnium-dev,krmcbride/node:10-dev'
  node_12-buster-base:
    <<: *defaults
    environment:
      context: ./build/node/12-buster-base
      image: 'krmcbride/node:12-buster-base'
      tags: 'krmcbride/node:erbium-buster-base,krmcbride/node:erbium-buster,krmcbride/node:erbium,krmcbride/node:12-buster,krmcbride/node:12'
  node_12-buster-dev:
    <<: *defaults
    environment:
      context: ./build/node/12-buster-dev
      image: 'krmcbride/node:12-buster-dev'
      tags: 'krmcbride/node:erbium-buster-dev,krmcbride/node:erbium-dev,krmcbride/node:12-dev'


workflows:
  version: 2
  build:
    jobs:
      - make

      - debian_stretch-base:
          filters: { branches: { only: [ master ] } }
          requires:
          - make
      - debian_stretch-dev:
          filters: { branches: { only: [ master ] } }
          requires:
          - debian_stretch-base
      - debian_buster-base:
          filters: { branches: { only: [ master ] } }
          requires:
          - make
      - debian_buster-dev:
          filters: { branches: { only: [ master ] } }
          requires:
          - debian_buster-base

      - java_8-stretch-base:
          filters: { branches: { only: [ master ] } }
          requires:
          - make
      - java_8-stretch-dev:
          filters: { branches: { only: [ master ] } }
          requires:
          - java_8-stretch-base

      - node_10-stretch-base:
          filters: { branches: { only: [ master ] } }
          requires:
          - make
      - node_10-stretch-dev:
          filters: { branches: { only: [ master ] } }
          requires:
          - node_10-stretch-base
      - node_12-buster-base:
          filters: { branches: { only: [ master ] } }
          requires:
          - make
      - node_12-buster-dev:
          filters: { branches: { only: [ master ] } }
          requires:
          - node_12-buster-base

