version: 2


defaults: &defaults
  docker:
    - image: 'krmcbride/docker@sha256:13a3b2717fbfb13ca32db8c8789cf855560884e264ee83e787f3dd55bced2bfd'
  working_directory: /usr/src/app
  steps:
    - setup_remote_docker
    - attach_workspace:
        at: /usr/src/app
    - run: 
        name: Login
        command: docker login -u ${docker_username} -p ${docker_password}
    - run: 
        name: Pull
        command: docker pull $image || true
    - run: 
        name: Build
        command: docker build --cache-from $image -t $image $context
    - deploy:
          name: Push
          command: docker push $image


jobs:
  make:
    docker:
      - image: 'krmcbride/docker@sha256:13a3b2717fbfb13ca32db8c8789cf855560884e264ee83e787f3dd55bced2bfd'
    working_directory: /usr/src/app
    steps:
      - checkout
      - run: make
      - persist_to_workspace:
          root: /usr/src/app
          paths: .

  alpine_34_base:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.4-base'
      context: ./build/alpine/3.4-base
  alpine_34_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.4-dev'
      context: ./build/alpine/3.4-dev
  alpine_36_base:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.6-base'
      context: ./build/alpine/3.6-base
  alpine_36_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/alpine:3.6-dev'
      context: ./build/alpine/3.6-dev

  debian_8_base:
    <<: *defaults
    environment:
      image: 'krmcbride/debian:8-base'
      context: ./build/debian/8-base
  debian_8_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/debian:8-dev'
      context: ./build/debian/8-dev

  java_8_alpine_base:
    <<: *defaults
    environment:
      image: 'krmcbride/java:8-alpine-base'
      context: ./build/java/8-alpine-base
  java_8_alpine_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/java:8-alpine-dev'
      context: ./build/java/8-alpine-dev
  java_8_debian_base:
    <<: *defaults
    environment:
      image: 'krmcbride/java:8-debian-base'
      context: ./build/java/8-debian-base
  java_8_debian_dev:
    <<: *defaults
    environment:
      image: 'krmcbride/java:8-debian-dev'
      context: ./build/java/8-debian-dev



workflows:
  version: 2
  build:
    jobs:
      - make

      - alpine_34_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - alpine_34_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_34_base
      - alpine_36_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - alpine_36_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_36_base

      - debian_8_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - debian_8_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_8_base
      - debian_9_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - make
      - debian_9_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_9_base

      - java_8_alpine_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_36_base
      - java_8_alpine_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - alpine_36_dev
      - java_8_debian_base:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_9_base
      - java_8_debian_dev:
          filters: { branches: { only: [ master ] } }
          requires:
            - debian_9_dev

