defaults: &defaults
  working_directory: /usr/src/app
  docker:
    - image: 'krmcbride/docker:17.03-ci'

version: 2
jobs:
  alpine_base:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: docker login
          command: docker login -u ${docker_username} -p ${docker_password}
      - run: 
          name: Pull alpine:3.6-base
          command: docker pull krmcbride/alpine:3.6-base
      - run: 
          name: Build alpine:3.6-base
          working_directory: ./alpine/3.6-base
          command: docker build --cache-from krmcbride/alpine:3.6-base -t krmcbride/alpine:3.6-base .
      - deploy:
          name: Push alpine:3.6-base
          command: docker push krmcbride/alpine:3.6-base
  alpine_dev:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: docker login
          command: docker login -u ${docker_username} -p ${docker_password}
      - run: 
          name: Pull alpine:3.6-dev
          command: docker pull krmcbride/alpine:3.6-dev
      - run: 
          name: Build alpine:3.6-dev
          working_directory: ./alpine/3.6-dev
          command: docker build --cache-from krmcbride/alpine:3.6-dev -t krmcbride/alpine:3.6-dev .
      - deploy:
          name: Push alpine:3.6-dev
          command: docker push krmcbride/alpine:3.6-dev
  node_boron_dev:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: docker login
          command: docker login -u ${docker_username} -p ${docker_password}
      - run: 
          name: Pull node:boron-dev
          command: docker pull krmcbride/node:boron-dev
      - run: 
          name: Build node:boron-dev
          working_directory: ./node/boron-dev
          command: docker build --cache-from krmcbride/node:boron-dev -t krmcbride/node:boron-dev .
      - deploy:
          name: Push node:boron-dev
          command: docker push krmcbride/node:boron-dev

workflows:
  version: 2
  build_dockerfiles:
    jobs:
      - alpine_base
      - alpine_dev:
          requires:
            - alpine_base
      - node_boron_dev:
          requires:
            - alpine_dev:
