FROM krmcbride/debian:8

# Git and ssh are required by package managers
RUN apt-get update && apt-get install -y --no-install-recommends \
        openssh-client \
        git \
    && rm -rf /var/lib/apt/lists/*

{{ .Env.buildpack }}

{{ .Env.upstream }}

