FROM node:16.13.1-bullseye

{{ .Env.mixin_bullseye_base }}

# Git and ssh are required by package managers
# python >3.6 is required by node-gyp, this should install 3.9
RUN apt-get update && apt-get install -y --no-install-recommends \
        openssh-client \
        git \
        python3 \
    && rm -rf /var/lib/apt/lists/*

