FROM krmcbride/debian:{{ .Env.version }}

RUN apt-get update \
  && apt-get remove -y --purge \
    vim.tiny \
  && apt-get install -y --no-install-recommends \
    man \
    perl \
    less \
    git \
    openssh-client \
    vim \
    ctags \
    zsh \
    bc \
    rsync \
  && rm -rf /var/lib/apt/lists/ \
  && git clone https://github.com/amix/vimrc.git /usr/local/vim_runtime \
  && ( \
    cd /usr/local/vim_runtime \
    && git checkout -b tmp 391f8b5c0680becede604ca84a60ed57f56e42bd \
    && rm -rf .git \
  ) \
  && git clone https://github.com/robbyrussell/oh-my-zsh.git /usr/local/oh-my-zsh \
  && ( \
    cd /usr/local/oh-my-zsh \
    && git checkout -b tmp d848c94804918138375041a9f800f401bec12068 \
    && rm -rf .git \
  ) \
  && git clone https://github.com/bhilburn/powerlevel9k.git  /usr/local/oh-my-zsh/custom/themes/powerlevel9k \
  && ( \
    cd /usr/local/oh-my-zsh/custom/themes/powerlevel9k \
    && git checkout -b tmp 4be16020b7cd7241b75c23db9f5bd3d4fce84686 \
    && rm -rf .git \
  )

ENV DOCKER_CHANNEL="stable" \
    DOCKER_VERSION="17.12.0-ce" \
    DOCKER_COMPOSE_VERSION="1.18.0"
RUN set -ex; \
    dockerArch='x86_64'; \
    if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
        echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
        exit 1; \
    fi; \
    \
    tar --extract \
        --file docker.tgz \
        --strip-components 1 \
        --directory /usr/local/bin/ \
    ; \
    rm docker.tgz; \
    dockerd -v; \
    docker -v; \
    curl -fL "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`" > /usr/local/bin/docker-compose; \
    chmod +x /usr/local/bin/docker-compose; \
    docker-compose -v

COPY diff-so-fancy/diff-* todo.txt/todo.sh /usr/local/bin/
COPY my_configs.vim /usr/local/vim_runtime/
COPY *.aliases.bash /usr/local/bash-it/aliases/enabled/
COPY *.completion.bash /usr/local/bash-it/completion/enabled/
COPY *.plugin.bash /usr/local/bash-it/plugins/enabled/
COPY omz-custom/ /usr/local/oh-my-zsh/custom/
COPY gitconfig /etc/
COPY dotfiles/.vimrc dotfiles/.zshrc /root/

CMD ["/bin/zsh"]
