FROM krmcbride/debian:{{ .Env.version }}

RUN apt-get update \
  && apt-get remove -y --purge \
    vim.tiny \
  && apt-get install -y --no-install-recommends \
    man \
    perl \
    less \
    git \
    openssh-client \
    vim \
    ctags \
    zsh \
    bc \
    rsync \
  && rm -rf /var/lib/apt/lists/ \
  && git clone https://github.com/amix/vimrc.git /usr/local/vim_runtime \
  && ( \
    cd /usr/local/vim_runtime \
    && git checkout -b tmp a6b64938eb43f5c1e09b9218177d90f40b622e70 \
    && rm -rf .git \
  ) \
  && git clone https://github.com/robbyrussell/oh-my-zsh.git /usr/local/oh-my-zsh \
  && ( \
    cd /usr/local/oh-my-zsh \
    && git checkout -b tmp 7f6e6cf346268a6d2cdf6fe167a60827aab53f0b \
    && rm -rf .git \
  ) \
  && git clone https://github.com/denysdovhan/spaceship-prompt.git /usr/local/oh-my-zsh/custom/themes/spaceship-prompt \
  && ( \
    cd /usr/local/oh-my-zsh/custom/themes/spaceship-prompt \
    && git checkout -b tmp d9f25e14e7bec4bef223fd8a9151d40b8aa868fa \
    && ln -s /usr/local/oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme /usr/local/oh-my-zsh/custom/themes/spaceship.zsh-theme \
    && rm -rf .git \
  )

ENV DOCKER_CHANNEL="stable" \
    DOCKER_VERSION="18.09.6" \
    DOCKER_COMPOSE_VERSION="1.22.0" \
    KUBECTL_VERSION="1.12.9"
RUN set -ex; \
    dockerArch='x86_64'; \
    if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
        echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
        exit 1; \
    fi; \
    \
    tar --extract \
        --file docker.tgz \
        --strip-components 1 \
        --directory /usr/local/bin/ \
    ; \
    rm docker.tgz; \
    dockerd -v; \
    docker -v; \
    curl -fL "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`" > /usr/local/bin/docker-compose; \
    chmod +x /usr/local/bin/docker-compose; \
    docker-compose -v; \
    curl -fsSLO --compressed "https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl"; \
    chmod +x kubectl; \
    mv kubectl /usr/local/bin/kubectl; \
    kubectl version --client --short; \
    curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator; \
    chmod +x ./aws-iam-authenticator; \
    mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator; \
    cp /usr/local/bin/aws-iam-authenticator /usr/local/bin/heptio-authenticator-aws;

COPY diff-so-fancy/diff-* todo.txt/todo.sh /usr/local/bin/
COPY my_configs.vim /usr/local/vim_runtime/
COPY *.aliases.bash /usr/local/bash-it/aliases/enabled/
COPY *.completion.bash /usr/local/bash-it/completion/enabled/
COPY *.plugin.bash /usr/local/bash-it/plugins/enabled/
COPY omz-custom/ /usr/local/oh-my-zsh/custom/
COPY gitconfig /etc/
COPY dotfiles/.vimrc dotfiles/.zshrc /root/

CMD ["/bin/zsh"]
