FROM alpine:{{ .Env.version }}

RUN apk add --no-cache \
      tzdata \
    && cp /usr/share/zoneinfo/America/Los_Angeles /etc/localtime \
    && echo "America/Los_Angeles" > /etc/timezone \
    && date \
    && apk del tzdata \
    && apk add --no-cache \
      bash \
      ca-certificates \
      curl \
    && mkdir -p /usr/src/app

# bash
COPY bash-it/ /usr/local/bash-it/
COPY dotfiles/.bashrc /root/

WORKDIR /root
CMD ["/bin/bash"]
