FROM krmcbride/alpine:{{ .Env.version }}-base

RUN apk add --no-cache \
    perl \
    less \
    git \
    openssh-client \
    vim \
    ctags \
    ncurses \
    zsh \
  && git clone https://github.com/amix/vimrc.git /usr/local/vim_runtime \
  && ( \
    cd /usr/local/vim_runtime \
    && git checkout 391f8b5c0680becede604ca84a60ed57f56e42bd \
    && rm -rf .git \
  ) \
  && git clone https://github.com/robbyrussell/oh-my-zsh.git /usr/local/oh-my-zsh \
  && ( \
    cd /usr/local/oh-my-zsh \
    && git checkout d848c94804918138375041a9f800f401bec12068 \
    && rm -rf .git \
  )

COPY diff-* /usr/bin/
COPY my_configs.vim /usr/local/vim_runtime/
COPY *.aliases.bash /usr/local/bash-it/aliases/enabled/
COPY *.completion.bash /usr/local/bash-it/completion/enabled/
COPY *.plugin.bash /usr/local/bash-it/plugins/enabled/
COPY *aliases.zsh /usr/local/oh-my-zsh/custom/
COPY gitconfig /etc/
COPY dotfiles/.vimrc ./dotfiles/.zshrc /root/

CMD ["/bin/zsh"]
