FROM krmcbride/alpine:{{ .Env.version }}

RUN apk add --no-cache \
    py-pip \
    perl \
    less \
    git \
    openssh-client \
    vim \
    ctags \
    ncurses \
    zsh \
    bc \
    rsync \
  && git clone https://github.com/amix/vimrc.git /usr/local/vim_runtime \
  && ( \
    cd /usr/local/vim_runtime \
    && git checkout -b tmp a6b64938eb43f5c1e09b9218177d90f40b622e70 \
    && rm -rf .git \
  ) \
  && git clone https://github.com/robbyrussell/oh-my-zsh.git /usr/local/oh-my-zsh \
  && ( \
    cd /usr/local/oh-my-zsh \
    && git checkout -b tmp 7f6e6cf346268a6d2cdf6fe167a60827aab53f0b \
    && rm -rf .git \
  ) \
  && git clone https://github.com/bhilburn/powerlevel9k.git  /usr/local/oh-my-zsh/custom/themes/powerlevel9k \
  && ( \
    cd /usr/local/oh-my-zsh/custom/themes/powerlevel9k \
    && git checkout -b tmp 358c105de7aa5e8109788adf65c08c44e368d418 \
    && rm -rf .git \
  )

ENV DOCKER_CHANNEL="stable" \
    DOCKER_VERSION="18.03.1-ce" \
    DOCKER_COMPOSE_VERSION="1.21.1"
RUN set -ex; \
    dockerArch='x86_64'; \
    if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
        echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
        exit 1; \
    fi; \
    \
    tar --extract \
        --file docker.tgz \
        --strip-components 1 \
        --directory /usr/local/bin/ \
    ; \
    rm docker.tgz; \
    dockerd -v; \
    docker -v; \
    pip install 'docker-compose=='${DOCKER_COMPOSE_VERSION}; \
    docker-compose -v

COPY diff-so-fancy/diff-* todo.txt/todo.sh /usr/local/bin/
COPY my_configs.vim /usr/local/vim_runtime/
COPY *.aliases.bash /usr/local/bash-it/aliases/enabled/
COPY *.completion.bash /usr/local/bash-it/completion/enabled/
COPY *.plugin.bash /usr/local/bash-it/plugins/enabled/
COPY omz-custom/ /usr/local/oh-my-zsh/custom/
COPY gitconfig /etc/
COPY dotfiles/.vimrc ./dotfiles/.zshrc /root/

CMD ["/bin/zsh"]
